##################################################################################
# Cloudify Docker built in types and plugins definitions.
##################################################################################

plugins:
  docker:
    executor: host_agent
    source: https://github.com/cloudify-cosmo/cloudify-docker-plugin/archive/master.zip

node_types:

  cloudify.docker.Image:
    derived_from: cloudify.node.Root
    properties:
      resource_id:
        description: The image tag.
        type: string 
      use_existing_resource:
        description: Whether the image already exists or not.
        type: boolean
        default: false

  cloudify.docker.BuildImage:
    derived_from: cloudify.docker.Image
    properties:
      resource_id:
        description: The image tag.
        type: string 
      use_existing_resource:
        description: Whether the image already exists or not.
        type: boolean
        default: false
      path:
        description: Path to the directory containing the Dockerfile.
        type: string
      fileobj: A file object to use as the Dockerfile. (Or a file-like object).
        type: string
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: docker.docker_plugin.task.build
          description: Creates an image from a docker build file.
        delete:
          implementation: docker.docker_plugin.task.rmi
          description: Removes an image.

  cloudify.docker.ImportImage:
    derived_from: cloudify.docker.Image
    properties:
      resource_id:
        description: The image tag.
        type: string 
      use_existing_resource:
        description: Whether the image already exists or not.
        type: boolean
        default: false
      src:
        description: Path to tarfile or URL.
        type: string
      image:
        description: Use another image like the FROM Dockerfile parameter.
        type: string
        default: ''
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: docker.docker_plugin.task.import_image
          description: Create a new filesystem image from the contents of a tarball.
        delete:
          implementation: docker.docker_plugin.task.rmi
          description: Removes an image.

  cloudify.docker.container:
    derived_from: cloudify.nodes.Container
    properties:
      resource_id:
        description: The image tag.
        type: string 
      use_existing_resource:
        description: Whether the image already exists or not.
        type: boolean
        default: false
      image:
        description: The image to run.
        type: string
        default: ''
      ports:
        description: >
          Key value pairs of port bindings as provided to the start function.
          The create function is designed to get only the keys for assignment
          of the ports parameter.
        default: []
      volumes:
        description: >
          A list of dictinaries describing volume mounts as described in the
          Using Volumes article in docker-py readthedocs.
        default: []
      params: {}
        description: Any parameters in the create_container function that are not mentioned here.
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: docker.docker_plugin.task.create_container
          description: Creates a container from an image.
        start:
          implementation: docker.docker_plugin.task.start
          description:  Runs a container.
        stop:
          implementation: docker.docker_plugin.task.stop
          description: Stops a container.
        delete:
          implementation: docker.docker_plugin.task.remove_container
          description: Deletes a container.
      cloudify.interfaces.validation:
        commit:
          implementation: docker.docker_plugin.task.commit
          description: Create a new image from a container's changes.
      cloudify.interfaces.docker_lifecycle:
        attach:
          implementation: docker.docker_plugin.task.attach
          description: Attach to a running container.
        copy:
          implementation: docker.docker_plugin.task.copy
          description: Copy files/folders from a container's filesystem to the host path.
        execute:
          implementation: docker.docker_plugin.task.execute
          description: Run a command in a new container.
        export:
          implementation: docker.docker_plugin.task.export
          description:  Stream the contents of a container as a tar archive.
        inspect:
          implementation: docker.docker_plugin.task.inspect
          description: Return low-level information on a container

relationships:

  cloudify.docker.container_based_on_image:
    derived_from: cloudify.relationships.node_depends_on
