##################################################################################
# Cloudify Docker built in types and plugins definitions.
##################################################################################

plugins:
  docker:
    executor: host_agent
    source: https://github.com/cloudify-cosmo/cloudify-docker-plugin/archive/master.zip

node_types:

  cloudify.docker.Image:
    derived_from: cloudify.node.Root
    properties:
      resource_id:
        description: The name of a repository or an image.
        type: string 
      use_existing_resource:
        description: Whether the image already exists or not.
        type: boolean
        default: false
      tag:
        description: The tag.
        type: string
      params:
        description: Any other parameters allowed by the API call that are not listed.
        default: {}
    interfaces:
        create:
          implementation: docker.docker_plugin.tasks.pull
          description: Pull an image or a repository from a Docker registry server.
        delete:
          implementation: docker.docker_plugin.tasks.remove_image
          description: Removes an image.
          inputs:
            force: false
            noprune: false

  cloudify.docker.BuildImage:
    derived_from: cloudify.docker.Image
    properties:
      resource_id:
        description: The name of a repository or an image.
        type: string 
        default: ''
      use_existing_resource:
        description: Whether the image already exists or not.
        type: boolean
        default: false
      params:
        description: Any parameters allowed by the API call that are not listed.
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: docker.docker_plugin.tasks.build
          description: Build an image from a Dockerfile.

  cloudify.docker.ImportImage:
    derived_from: cloudify.docker.Image
    properties:
      resource_id:
        description: The image tag.
        type: string 
      use_existing_resource:
        description: Whether the image already exists or not.
        type: boolean
        default: false
      src:
        description: Path to tarfile or URL.
        type: string
      params:
        description: Any other parameters allowed by the API call that are not listed.
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: docker.docker_plugin.tasks.import_image
          description: Create a new filesystem image from the contents of a tarball.

  cloudify.docker.container:
    derived_from: cloudify.nodes.Container
    properties:
      resource_id:
        description: The container to start.
        type: string 
      use_existing_resource:
        description: Whether the image already exists or not.
        type: boolean
        default: true
      image:
        description: >
          The image to create from if not using external resource.
      ports:
        description: >
          Key value pairs of port bindings as provided to the start function.
          The create function is designed to get only the keys for assignment
          of the ports parameter.
        default: []
      volumes:
        description: >
          A list of dictinaries describing volume mounts as described in the
          Using Volumes article in docker-py readthedocs.
        default: []
      params: {}
        description: Any parameters in the create_container function that are not mentioned here.
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: docker.docker_plugin.tasks.create_container
          description: Creates a container from an image.
        start:
          implementation: docker.docker_plugin.tasks.start
          description:  Runs a container.
          inputs:
            retry_interval: 10
        stop:
          implementation: docker.docker_plugin.tasks.stop
          description: Stops a container.
          inputs:
            timeout: 30
        delete:
          implementation: docker.docker_plugin.tasks.remove_container
          description: Deletes a container.
          inputs:
            v: false
            link: true
            force: false
      cloudify.interfaces.validation:
        commit:
          implementation: docker.docker_plugin.tasks.commit
          description: Create a new image from a container's changes.
      cloudify.interfaces.docker_lifecycle:
        attach:
          implementation: docker.docker_plugin.tasks.attach
          description: Attach to a running container.
        copy:
          implementation: docker.docker_plugin.tasks.copy
          description: Copy files/folders from a container's filesystem to the host path.
        execute:
          implementation: docker.docker_plugin.tasks.execute
          description: Run a command in a new container.
        export:
          implementation: docker.docker_plugin.tasks.export
          description:  Stream the contents of a container as a tar archive.
        inspect:
          implementation: docker.docker_plugin.tasks.inspect
          description: Return low-level information on a container

relationships:
  cloudify.docker.container_based_on_image:
    derived_from: cloudify.relationships.node_depends_on
