##################################################################################
# Cloudify Docker built in types and plugins definitions.
##################################################################################

plugins:
  docker:
    executor: host_agent
    source: https://github.com/cloudify-cosmo/cloudify-docker-plugin/archive/master.zip

node_types:

  cloudify.docker.Image:
    derived_from: cloudify.nodes.Root
    properties:
      resource_id:
        description: The name of a repository or an image.
        type: string 
      use_external_resource:
        description: Whether the image already exists or not.
        type: boolean
        default: false
      install_agent:
        description: whether to install the cloudify agent on the host
        type: boolean
        default: true
      params:
        description: Any parameters allowed by the API call that are not listed.
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          #    Identical to the docker pull command.
          implementation: docker.docker_plugin.tasks.pull
        delete:
          #    Remove an image. Similar to the docker rmi command.
          implementation: docker.docker_plugin.tasks.remove_image
          inputs:
            force:
              description: Force removal of the image
              type: boolean
              default: false
            noprune:
              description: Do not delete untagged parents
              type: boolean
              default: false

  cloudify.docker.BuildImage:
    derived_from: cloudify.docker.Image
    properties:
      resource_id:
        description: The name of a repository or an image.
        type: string 
        default: ''
      use_external_resource:
        description: Whether the image already exists or not.
        type: boolean
        default: false
      params:
        description: Any parameters allowed by the API call that are not listed.
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          #    Similar to the docker build command. Either path or fileobj needs
          #    to be set. path can be a local path (to a directory containing a
          #    Dockerfile) or a remote URL. fileobj must be a readable file like object
          #    to a Dockerfile.
          implementation: docker.docker_plugin.tasks.build

  cloudify.docker.ImportImage:
    derived_from: cloudify.docker.Image
    properties:
      resource_id:
        description: The repository to create.
        type: string 
      use_external_resource:
        description: Whether the image already exists or not.
        type: boolean
        default: false
      src:
        description: Path to tarfile or URL.
        type: string
      params:
        description: Any other parameters allowed by the API call that are not listed.
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          #    Identical to the docker import command. If src is a string or unicode string
          #    it will be treated as a URL to fetch the image from. To import an image from
          #    the local machine src needs to be a file like object or bytes collection.
          #    To import from a tarball use your absolute path to your tarball.
          implementation: docker.docker_plugin.tasks.import_image

  cloudify.docker.Container:
    derived_from: cloudify.nodes.Container
    properties:
      resource_id:
        description: The name of the Docker container.
        type: string 
      use_external_resource:
        description: Whether the container already exists or not.
        type: boolean
        default: false
      image:
        description: >
          The image to create from if not using external resource.
      ports:
        description: >
          Key value pairs of port bindings as provided to the start function.
          The create function is designed to get only the keys for assignment
          of the ports parameter.
        default: []
      install_agent:
        description: whether to install the cloudify agent on the host
        type: boolean
        default: true
      params:
        description: >
          Any parameters in the create_container function that are not mentioned here.
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          #    Creates a container that can then be .start() ed.
          #    Parameters are similar to those for the docker run command
          #    except it does not support the attach options.
          implementation: docker.docker_plugin.tasks.create_container
        start:
          #    Similar to the docker start command, but does not support attach options. 
          implementation: docker.docker_plugin.tasks.start
          inputs:
            retry_interval:
              description: >
                Before finishing start checks to see that all processes
                on the container are ready. This is the interval between
                checks.
              type: integer
              default: 10
        stop:
          #    Stops a container. Similar to the docker stop command.
          implementation: docker.docker_plugin.tasks.stop
          inputs:
            retry_interval:
              description: >
                Before finishing start checks to see that all processes
                on the container are ready. This is the interval between
                checks.
              type: integer
              default: 10
            timeout:
              description: >
                Timeout in seconds to wait for the container to stop before sending a SIGKILL
              type: integer
              default: 30
        delete:
          #    Remove a container. Similar to the docker rm command.
          implementation: docker.docker_plugin.tasks.remove_container
          inputs:
            v:
              description: Remove the volumes associated with the container
              type: boolean
              default: false
            link:
              description: Remove the specified link and not the underlying container
              type: boolean
              default: true
            force: 
              description: Force the removal of a running container (uses SIGKILL)
              type: boolean
              default: false

relationships:
  cloudify.docker.container_depends_on_image:
    derived_from: cloudify.relationships.depends_on
