##################################################################################
# Cloudify Docker built in types and plugins definitions.
##################################################################################

plugins:
    docker:
        executor: host_agent
        source: https://github.com/cloudify-cosmo/cloudify-docker-plugin/archive/CFY-1792-docker-plugin-pull-support.zip
