##################################################################################
# Cloudify Docker built in types and plugins definitions.
##################################################################################

plugins:
  docker:
    executor: host_agent
    source: https://github.com/cloudify-cosmo/cloudify-docker-plugin/archive/master.zip

node_types:

  cloudify.docker.Image:
    derived_from: cloudify.nodes.Root
    properties:
      tag:
        description: The image tag.
    interfaces:
      cloudify.interfaces.lifecycle:
        delete:
          implementation: docker.docker_plugin.tasks.remove_image
          inputs:
            force:
              description: Force removal of the image
              type: boolean
              default: false
            noprune:
              description: Do not delete untagged parents
              type: boolean
              default: false

  cloudify.docker.ImageFromScratch:
    derived_from: cloudify.docker.Image
    properties:
      params: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: docker.docker_plugin.tasks.build

  cloudify.docker.RepositoryImage:
    derived_from: cloudify.docker.Image
    properties:
      repository:
        description: The repository to pull.
      params:
        description: Any parameters allowed by the API call that are not listed.
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: docker.docker_plugin.tasks.pull

  cloudify.docker.FileSystemImage:
    derived_from: cloudify.docker.Image
    properties:
      repository: 
        description: The repository to create.
      src:
        description: Path to tarfile or URL.
        type: string
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: docker.docker_plugin.tasks.import_image

  cloudify.docker.Container:
    derived_from: cloudify.nodes.Container
    properties:
      name:
        description: The name of the Docker container.
        type: string 
      use_external_resource:
        description: Whether the container already exists or not.
        type: boolean
        default: false
      image:
        description: >
          The image to create from if not using external resource.
      ports:
        description: >
          Key value pairs of port bindings as provided to the start function.
          The create function is designed to get only the keys for assignment
          of the ports parameter.
        default: {}
      params:
        description: >
          Any parameters in the create_container function that are not mentioned here.
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: docker.docker_plugin.tasks.create_container
        start:
          implementation: docker.docker_plugin.tasks.start
          inputs:
            retry_interval:
              description: >
                Before finishing start checks to see that all processes
                on the container are ready. This is the interval between
                checks.
              type: integer
              default: 10
        stop:
          implementation: docker.docker_plugin.tasks.stop
          inputs:
            retry_interval:
              description: >
                Before finishing start checks to see that all processes
                on the container are ready. This is the interval between
                checks.
              type: integer
              default: 10
            timeout:
              description: >
                Timeout in seconds to wait for the container to stop before sending a SIGKILL
              type: integer
              default: 30
        delete:
          implementation: docker.docker_plugin.tasks.remove_container
          inputs:
            v:
              description: Remove the volumes associated with the container
              type: boolean
              default: false
            link:
              description: Remove the specified link and not the underlying container
              type: boolean
              default: true
            force: 
              description: Force the removal of a running container (uses SIGKILL)
              type: boolean
              default: false

relationships:
  cloudify.docker.container_depends_on_image:
    derived_from: cloudify.relationships.depends_on
